swagger: "2.0"

info:
  version: "0.0.1-alpha"
  title: Fullstop API
  description: Audit reporting

schemes:
  - https

basePath: /api/

consumes:
  - application/json
produces:
  - application/json

definitions:
  Violation:
    type: object
    properties:
      eventId:
        type: string
        example: cd768599e1bb41c38279c26254feff5cf57bf967
      accountId:
        type: string
        example: 123456789
      region:
        type: string
        example: "eu-west-1"
      message:
        type: string
        example: "The instance i-3w4fdsa is running in the wrong region"
      violationObject:
        type: object
        example: ""
      comment:
        type: string
        example: "Was a patch on Friday and I was alone in the office"
      checked:
        type: boolean
        example: "true"


  LogObj:
    type: object
    properties:
      log-type:
        type: string
        enum:
          - AUDIT_LOG
          - USER_DATA
      instanceId:
        type: string
        example: "i-123kd"
      accountId:
        type: string
        example: "1233456568"
      region:
        type: string
        example: "eu-west-1"
      instanceBootTime:
        type: string
        format: date-time
        example: 2015-05-21T10:24:47.788-02:00
      logData:
        type: string
        example: ""

  Acknowledged:
    type: object
    properties:
      checked:
        type: boolean
        example: true
      message:
        type: string
        example: "Was a patch on Friday and I was alone in the office"

paths:

  ## Fullstop API v1

  /api/violations:
    get:
      summary: violations
      description: Get all violations
      tags:
        - Fullstop API
      operationId: violations
      responses:
        "200":
          description: List of all violations
          schema:
            type: array
            items:
              $ref: "#/definitions/Violation"

  /api/account-ids:
    get:
      summary: accountIds
      description: Get all account ids
      tags:
        - Fullstop API
      operationId: account-id
      responses:
        "200":
          description: List of all account Ids
          schema:
            type: array
            items:
              type: string

  /api/account-violations/{account-id}:
    get:
      summary: Violations for one account
      description: Get all violations for one account
      tags:
        - Fullstop API
      operationId: accountViolations
      parameters:
        - name: account-id
          in: path
          type: string
          required: true
      responses:
        "200":
          description: List of all violations for one account
          schema:
            type: array
            items:
              $ref: "#/definitions/Violation"

  /api/violations/{id}:
    put:
      summary: Comment and acknowledged violation
      description: Comment and acknowledged violation
      tags:
        - Fullstop API
      operationId: acknowledgedViolations
      responses:
        "200":
          description: Violation updated successfully
      parameters:
        - name: id
          in: path
          type: integer
          required: true
        - name: acknowledged
          in: body
          required: true
          schema:
            $ref: "#/definitions/Acknowledged"
            description: Acknowledged metadata and object


  /api/instance-logs:
    post:
      summary: Put instance log in S3
      description: Add log for instance in S3
      tags:
        - Fullstop API
      operationId: instanceLogs
      responses:
        "201":
          description: Logs saved successfully
      parameters:
        - name: log
          in: body
          required: true
          schema:
            $ref: "#/definitions/LogObj"
            description: log metadata and object
