swagger: "2.0"

info:
  version: ""
  title: Fullstop API
  description: Audit reporting

schemes:
  - https

basePath: /api/

consumes:
  - application/json
produces:
  - application/json

definitions:
  ViolationType:
    type: object
    properties:
      id:
        type: string
        example: "MISSING_USERDATA"
      version:
        type: integer
        format: int64
        example: 3
      help_text:
        type: string
        example: ""
      violation_severity:
        type: integer
        example: 1
      is_audit_relevant:
        type: boolean
      created:
        type: string
        format: date-time
        example: 2015-05-21T10:24:47.788-02:00
      created_by:
        type: string
        example: "John Die"
      last_modified:
        type: string
        format: date-time
        example: 2015-05-21T10:24:47.788-02:00
      last_modified_by:
        type: string
        example: "John Dae"
  
  Violation:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 1
      version:
        type: integer
        format: int64
        example: 3
      eventId:
        type: string
        example: cd768599e1bb41c38279c26254feff5cf57bf967
      account_id:
        type: string
        example: 123456789
      region:
        type: string
        example: "eu-west-1"
      meta_info:
        type: object
        example: ""
      instance_id:
        type: string
        example: "i-1234"
      plugin_fully_qualified_className:
        type: string
        example: "org.zalando.stups.fullstop.plugin.subnet.SubnetPlugin"
      violation_type:
        $ref: "#/definitions/ViolationType"
      comment:
        type: string
        example: "Was a patch on Friday and I was alone in the office"
      created:
        type: string
        format: date-time
        example: 2015-05-21T10:24:47.788-02:00
      created_by:
        type: string
        example: "John Die"
      last_modified:
        type: string
        format: date-time
        example: 2015-05-21T10:24:47.788-02:00
      last_modified_by:
        type: string
        example: "John Dae"


  LogObj:
    type: object
    properties:
      log_type:
        type: string
        enum:
          - AUDIT_LOG
          - USER_DATA
      instance_id:
        type: string
        example: "i-123kd"
      account_id:
        type: string
        example: "1233456568"
      region:
        type: string
        example: "eu-west-1"
      instance_boot_time:
        type: string
        format: date-time
        example: 2015-05-21T10:24:47.788-02:00
      log_data:
        type: string
        example: ""
  
  InstanceCount:
    type: object
    properties:
      version:
        type: string
        example: "1.0"
        description: Version ID
      date:
        type: string
        format: date-time
        example: "2012-08-12T09:00:00.000Z"
        description: When this instance count was noticed by fullstop
      instances:
        type: integer
        example: 3
        description: Number of instances
    required:
      - version
      - date
      - instances

paths:

  ## Fullstop API v1

  /api/violations/{id}:
    get:
      summary: violation
      description: Get one violation
      tags:
        - Fullstop API
      operationId: getViolation
      security:
        - oauth2: [uid]
      parameters:
        - name: id
          in: path
          type: integer
          format: int64
          required: true
      responses:
        "200":
          description: Violation
          schema:
            $ref: "#/definitions/Violation"

  /api/violations:
    get:
      summary: violations
      description: Get all violations
      tags:
        - Fullstop API
      operationId: violations
      security:
        - oauth2: [uid]
      parameters:
        - name: accounts
          in: query
          description: Include only violations in these accounts
          required: false
          type: array
          items:
            type: string
        - name: since
          in: query
          required: false
          type: string
          format: date-time
          description: Include only violations that happened after this point in time
        - name: last-violation
          in: query
          required: false
          type: integer
          format: int64
          description: Include only violations after the one with this id
        - name: checked
          in: query
          required: false
          type: boolean
          description: Include only violations where checked field equals this value
        - name: severity
          in: query
          required: false
          type: string
          enum:
            - CRITICAL_IMPACT
            - SIGNIFICANT_IMPACT
            - MINOR_IMPACT
            - LOW_IMPACT
          description: Include only violations where checked field equals this value
        - name: audit-relevant
          in: query
          required: false
          type: boolean
          description: Include only violations that re audit relevant
        - name: type
          in: query
          required: false
          type: string
          description: Include only violations with a certain type
      responses:
        "200":
          description: List of all violations
          schema:
            type: array
            items:
              $ref: "#/definitions/Violation"

  /api/violations/{id}/resolution:
    post:
      summary: Resolve and explain this violation
      description: Resolve and explain violation
      tags:
        - Fullstop API
      operationId: resolveViolations
      security:
        - oauth2: [uid]
      responses:
        "200":
          description: Violation resolved successfully
      parameters:
        - name: id
          in: path
          type: integer
          required: true
        - name: comment
          in: body
          required: true
          schema:
            type: string

  /api/violation-types:
    get:
      tags:
        - Fullstop API
      summary: Get all violation types
      responses:
        200:
          description: The list of all available violation types
          schema:
            type: array
            items:
              $ref: "#/definitions/ViolationType"

  /api/violations-count:
    get:
      summary: Count violations by accounts and types
      tags:
        - Fullstop API
      parameters:
        - name: accounts
          in: query
          description: a list of account ids for filtering, leave blank to request all accounts
          type: array
          items:
            type: string
          required: false
        - name: from
          in: query
          description: include only violations, that have been created after this timestamp
          type: string
          format: date-time
          required: false
        - name: to
          in: query
          description: include only violations, that have been created before this timestamp
          type: string
          format: date-time
          required: false
        - name: resolved
          in: query
          description: count only violations that have been resolved (true), or that are still open (false)
          type: boolean
          required: false
      responses:
        200:
          description: violation count by account and type
          schema:
            type: array
            items:
              type: object
              properties:
                account:
                  type: string
                type:
                  type: string
                quantity:
                  type: integer
                  format: int64

  /api/violations-count/{account}:
    get:
      summary: Count violations by accounts and types
      tags:
        - Fullstop API
      parameters:
        - name: account
          in: path
          description: an account id
          type: string
          required: true
        - name: from
          in: query
          description: include only violations, that have been created after this timestamp
          type: string
          format: date-time
          required: false
        - name: to
          in: query
          description: include only violations, that have been created before this timestamp
          type: string
          format: date-time
          required: false
        - name: resolved
          in: query
          description: count only violations that have been resolved (true), or that are still open (false)
          type: boolean
          required: false
      responses:
        200:
          description: violation count by account and type
          schema:
            type: array
            items:
              type: object
              properties:
                application:
                  type: string
                version:
                  type: string
                type:
                  type: string
                quantity:
                  type: integer
                  format: int64                  

  /api/instance-logs:
    post:
      summary: Put instance log in S3
      description: Add log for instance in S3
      tags:
        - Fullstop API
      operationId: instanceLogs
      security:
        - oauth2: [uid]
      responses:
        "201":
          description: Logs saved successfully
      parameters:
        - name: log
          in: body
          required: true
          schema:
            $ref: "#/definitions/LogObj"
            description: log metadata and object
  
  /api/lifecycle/{application}:
    get:
      summary: list app lifecycle
      description: |
        Lists application lifecycle
      tags:
        - Lifecycle
      parameters:
        - name: application
          in: path
          description: "ID of application"
          type: string
          required: true
        - name: from
          in: query
          type: string
          format: date-time
          required: true
          description: "Lifecycle start date"
        - name: to
          in: query
          type: string
          format: date-time
          required: false
          description: "Lifecycle end date"
      responses:
        200:
          description: Lists number of instances per version
          schema:
            type: array
            items:
              $ref: '#/definitions/InstanceCount'
  /api/lifecycle/{application}/{version}:
    get:
      summary: list app lifecycle
      description: |
        Lists application lifecycle
      tags:
        - Lifecycle
      parameters:
        - name: application
          in: path
          description: "ID of application"
          type: string
          required: true
        - name: version
          in: path
          description: "ID of version"
          type: string
          required: true
        - name: from
          in: query
          type: string
          format: date-time
          required: true
          description: "Lifecycle start date"
        - name: to
          in: query
          type: string
          format: date-time
          required: false
          description: "Lifecycle end date"
      responses:
        200:
          description: Lists number of instances for this version
          schema:
            type: array
            items:
              $ref: '#/definitions/InstanceCount'

securityDefinitions:
  oauth2:
    type: oauth2
    flow: password
    tokenUrl: https://example.com/oauth2/tokenUrl
    scopes:
      uid: Unique identifier of the user accessing the service.
